// generated by scripts/install-fonts.mjs — do not edit by hand
export const BUNDLED_FONTS: string[] = [
  "Archivo",
  "Exo",
  "Google Sans",
  "Jost",
  "Lato",
  "Metrophobic",
  "Montserrat",
  "Noto Sans",
  "Playfair Display",
  "Plus Jakarta Sans",
  "Poppins",
  "Roboto",
  "Sora",
  "Urbanist"
];
