// Self-host fonts into the app: copy a curated weight set per family from a
// source folder into public/fonts/, generate the @font-face stylesheet, and
// emit the family list for the picker. Re-runnable — drop more .ttf/.otf into
// the source folder and run again.
//
//   node scripts/install-fonts.mjs ["D:\\path\\to\\fonts"] [--all-widths]
//
// By default it self-hosts the 4 styles the editor can actually pick
// (Regular/Bold/Italic/BoldItalic = weight 400/700 × normal/italic) for each
// BASE family (width variants like *_Condensed are skipped unless --all-widths).

import { readdirSync, mkdirSync, rmSync, copyFileSync, writeFileSync, statSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const SRC = process.argv.find((a, i) => i >= 2 && !a.startsWith("--")) || "D:\\Only  office fonts";
const ALL_WIDTHS = process.argv.includes("--all-widths");

const outDir = resolve(root, "public", "fonts");
const WEIGHTS = { Thin: 100, ExtraLight: 200, Light: 300, Regular: 400, Medium: 500, SemiBold: 600, Bold: 700, ExtraBold: 800, Black: 900 };
// the editor only distinguishes normal/bold and normal/italic, so self-host just these
const WANT = new Set(["400|0", "700|0", "400|1", "700|1"]);

const camelToWords = s => s.replace(/_/g, " ").replace(/([a-z])([A-Z])/g, "$1 $2").replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2").replace(/\s+/g, " ").trim();

function parse(file) {
  const m = /^(.+?)-(.+)\.(ttf|otf)$/i.exec(file);
  if (!m) return null;
  const familyRaw = m[1];
  const styleTok = m[2];
  const italic = /Italic$/i.test(styleTok) ? 1 : 0;
  const wtok = styleTok.replace(/Italic$/i, "") || "Regular";
  const weight = WEIGHTS[wtok];
  if (weight === undefined) return null;
  if (!ALL_WIDTHS && familyRaw.includes("_")) return null; // skip Condensed/Expanded/... variants
  return { familyRaw, weight, italic, family: camelToWords(familyRaw), ext: m[3].toLowerCase() };
}

if (!existsSync(SRC)) {
  console.error(`Font source folder not found: ${SRC}`);
  process.exit(1);
}

// gather: family -> { "weight|italic" -> srcFile }
const fams = new Map();
let scanned = 0;
for (const f of readdirSync(SRC)) {
  if (!/\.(ttf|otf)$/i.test(f)) continue;
  scanned++;
  const p = parse(f);
  if (!p) continue;
  const key = `${p.weight}|${p.italic}`;
  if (!WANT.has(key)) continue;
  if (!fams.has(p.family)) fams.set(p.family, { family: p.family, files: new Map() });
  const fam = fams.get(p.family);
  if (!fam.files.has(key)) fam.files.set(key, f);
}

// reset output dir and copy
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const faces = [];
const families = [];
let bytes = 0;
for (const fam of [...fams.values()].sort((a, b) => a.family.localeCompare(b.family))) {
  if (!fam.files.size) continue;
  families.push(fam.family);
  for (const [key, srcFile] of fam.files) {
    const [weight, italic] = key.split("|");
    copyFileSync(resolve(SRC, srcFile), resolve(outDir, srcFile));
    bytes += statSync(resolve(outDir, srcFile)).size;
    const fmt = srcFile.toLowerCase().endsWith(".otf") ? "opentype" : "truetype";
    faces.push(
      `@font-face{font-family:"${fam.family}";font-style:${italic === "1" ? "italic" : "normal"};` +
      `font-weight:${weight};font-display:swap;src:url("${srcFile}") format("${fmt}");}`,
    );
  }
}

writeFileSync(resolve(outDir, "fonts.css"),
  `/* generated by scripts/install-fonts.mjs — do not edit by hand */\n${faces.join("\n")}\n`);

const tsDir = resolve(root, "src", "fonts");
mkdirSync(tsDir, { recursive: true });
writeFileSync(resolve(tsDir, "bundled.ts"),
  `// generated by scripts/install-fonts.mjs — do not edit by hand\n` +
  `export const BUNDLED_FONTS: string[] = ${JSON.stringify(families, null, 2)};\n`);

console.log(`Scanned ${scanned} files in ${SRC}`);
console.log(`Self-hosted ${families.length} families, ${faces.length} faces, ${(bytes / 1048576).toFixed(1)} MB`);
console.log(`Families: ${families.join(", ")}`);
console.log(`→ public/fonts/fonts.css, public/fonts/*.ttf, src/fonts/bundled.ts`);
