// Self-host fonts into the app: copy each weight from a source folder into
// public/fonts/, generate the @font-face stylesheet, and emit the family list
// for the picker. Re-runnable — drop more .ttf/.otf into the source folder and
// run again.
//
//   node scripts/install-fonts.mjs ["D:\\path\\to\\fonts"] [--all-widths]
//
// Regular/Bold (+italics) live under the BASE family ("Montserrat") so the Bold
// button works. Every OTHER weight (Thin/ExtraLight/Light/Medium/SemiBold/
// ExtraBold/Black) is self-hosted as its OWN named family ("Montserrat SemiBold")
// — the way PowerPoint names weights and how .pptx decks reference them — so it
// renders on import and is selectable in the picker. Width variants like
// *_Condensed are skipped unless --all-widths.

import { readdirSync, mkdirSync, rmSync, copyFileSync, writeFileSync, statSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const SRC = process.argv.find((a, i) => i >= 2 && !a.startsWith("--")) || "D:\\Only  office fonts";
const ALL_WIDTHS = process.argv.includes("--all-widths");

const outDir = resolve(root, "public", "fonts");
const WEIGHTS = { Thin: 100, ExtraLight: 200, Light: 300, Regular: 400, Medium: 500, SemiBold: 600, Bold: 700, ExtraBold: 800, Black: 900 };

const camelToWords = s => s.replace(/_/g, " ").replace(/([a-z])([A-Z])/g, "$1 $2").replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2").replace(/\s+/g, " ").trim();

function parse(file) {
  const m = /^(.+?)-(.+)\.(ttf|otf)$/i.exec(file);
  if (!m) return null;
  const familyRaw = m[1];
  const styleTok = m[2];
  const italic = /Italic$/i.test(styleTok) ? 1 : 0;
  const wtok = styleTok.replace(/Italic$/i, "") || "Regular";
  const weight = WEIGHTS[wtok];
  if (weight === undefined) return null;
  if (!ALL_WIDTHS && familyRaw.includes("_")) return null; // skip Condensed/Expanded/... variants
  return { familyRaw, weight, wtok, italic, family: camelToWords(familyRaw), ext: m[3].toLowerCase() };
}

if (!existsSync(SRC)) {
  console.error(`Font source folder not found: ${SRC}`);
  process.exit(1);
}

// gather: family -> { "weight|italic" -> srcFile }
const fams = new Map();
let scanned = 0;
for (const f of readdirSync(SRC)) {
  if (!/\.(ttf|otf)$/i.test(f)) continue;
  scanned++;
  const p = parse(f);
  if (!p) continue;
  // Regular/Bold stay under the base family (Bold button toggles 400↔700);
  // every other weight becomes its own named family at css weight 400.
  const named = p.weight !== 400 && p.weight !== 700;
  const famName = named ? `${p.family} ${p.wtok}` : p.family;
  const cssWeight = named ? 400 : p.weight;
  const key = `${cssWeight}|${p.italic}`;
  if (!fams.has(famName)) fams.set(famName, { family: famName, files: new Map() });
  const fam = fams.get(famName);
  if (!fam.files.has(key)) fam.files.set(key, f);
}

// reset output dir and copy
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const faces = [];
const families = [];
let bytes = 0;
for (const fam of [...fams.values()].sort((a, b) => a.family.localeCompare(b.family))) {
  if (!fam.files.size) continue;
  families.push(fam.family);
  for (const [key, srcFile] of fam.files) {
    const [weight, italic] = key.split("|");
    copyFileSync(resolve(SRC, srcFile), resolve(outDir, srcFile));
    bytes += statSync(resolve(outDir, srcFile)).size;
    const fmt = srcFile.toLowerCase().endsWith(".otf") ? "opentype" : "truetype";
    faces.push(
      `@font-face{font-family:"${fam.family}";font-style:${italic === "1" ? "italic" : "normal"};` +
      `font-weight:${weight};font-display:swap;src:url("${srcFile}") format("${fmt}");}`,
    );
  }
}

writeFileSync(resolve(outDir, "fonts.css"),
  `/* generated by scripts/install-fonts.mjs — do not edit by hand */\n${faces.join("\n")}\n`);

const tsDir = resolve(root, "src", "fonts");
mkdirSync(tsDir, { recursive: true });
writeFileSync(resolve(tsDir, "bundled.ts"),
  `// generated by scripts/install-fonts.mjs — do not edit by hand\n` +
  `export const BUNDLED_FONTS: string[] = ${JSON.stringify(families, null, 2)};\n`);

// family/weight/italic -> filename map, for embedding fonts in exported .pptx
const manifest = [];
for (const fam of [...fams.values()].sort((a, b) => a.family.localeCompare(b.family))) {
  for (const [key, file] of fam.files) {
    const [weight, italic] = key.split("|");
    manifest.push({ family: fam.family, weight: Number(weight), italic: italic === "1", file });
  }
}
manifest.sort((a, b) => a.family.localeCompare(b.family) || a.weight - b.weight || Number(a.italic) - Number(b.italic));
writeFileSync(resolve(tsDir, "manifest.ts"),
  `// generated by scripts/install-fonts.mjs — do not edit by hand\n` +
  `export interface FontFile { family: string; weight: number; italic: boolean; file: string }\n` +
  `export const FONT_FILES: FontFile[] = ${JSON.stringify(manifest, null, 0)};\n`);

console.log(`Scanned ${scanned} files in ${SRC}`);
console.log(`Self-hosted ${families.length} families, ${faces.length} faces, ${(bytes / 1048576).toFixed(1)} MB`);
console.log(`Families: ${families.join(", ")}`);
console.log(`→ public/fonts/fonts.css, public/fonts/*.ttf, src/fonts/bundled.ts`);
